org:

service: bonzai-booking-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"

build:
  esbuild:
    minify: true

package:
  individually: true

functions:
  createBooking:
    handler: functions/createBooking/index.handler
    events:
      - httpApi:
          path: /bookings
          method: post

  deleteBooking:
    handler: functions/deleteBooking/index.handler
    events:
      - httpApi:
          path: /bookings/{id}
          method: delete

  getAllBookings:
    handler: functions/getAllBookings/index.handler
    events:
      - httpApi:
          path: /bookings
          method: get

  updateBooking:
    handler: functions/updateBooking/index.handler
    events:
      - httpApi:
          path: /bookings/{id}
          method: put

resources:
  Resources:
    bookings:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bookings
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
